<span>
<img src="http://www.sobigdata.eu/sites/default/files/logo-SoBigData-DEFINITIVO.png" width="180px" align="right"/>
</span>
<span>
<b>Author:</b> <a href="http://kdd.isti.cnr.it/people/riccardo-guidotti">Riccardo Guidotti</a><br/>
<b>Python version:</b>  3.x<br/>
</span>

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Load Data

In [3]:
df = pd.read_csv('data/iris.csv') 

In [4]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
len(df)

150

In [6]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [7]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

## Numpy

In [8]:
X = df.values

Shape

In [9]:
X.shape

(150, 5)

Element Indexing

In [10]:
X[0][0]

5.1

Row indexing

In [11]:
X[0]

array([5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], dtype=object)

Column Indexing

In [12]:
X[:, 0]

array([5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5.0,
       5.0, 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5.0, 5.5, 4.9, 4.4,
       5.1, 5.0, 4.5, 4.4, 5.0, 5.1, 4.8, 5.1, 4.6, 5.3, 5.0, 7.0, 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5.0, 5.9, 6.0, 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6.0, 5.7, 5.5, 5.5, 5.8, 6.0, 5.4, 6.0, 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5.0, 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6.0, 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6.0, 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9], dtype=object)

Conditional Indexing

In [13]:
X[X[:, 0] > 7]

array([[7.1, 3.0, 5.9, 2.1, 'Iris-virginica'],
       [7.6, 3.0, 6.6, 2.1, 'Iris-virginica'],
       [7.3, 2.9, 6.3, 1.8, 'Iris-virginica'],
       [7.2, 3.6, 6.1, 2.5, 'Iris-virginica'],
       [7.7, 3.8, 6.7, 2.2, 'Iris-virginica'],
       [7.7, 2.6, 6.9, 2.3, 'Iris-virginica'],
       [7.7, 2.8, 6.7, 2.0, 'Iris-virginica'],
       [7.2, 3.2, 6.0, 1.8, 'Iris-virginica'],
       [7.2, 3.0, 5.8, 1.6, 'Iris-virginica'],
       [7.4, 2.8, 6.1, 1.9, 'Iris-virginica'],
       [7.9, 3.8, 6.4, 2.0, 'Iris-virginica'],
       [7.7, 3.0, 6.1, 2.3, 'Iris-virginica']], dtype=object)

## Indexing

In [14]:
df['sepal_length'].head()  # df.sepal_length

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal_length, dtype: float64

In [15]:
cols = ['sepal_length', 'petal_length']
df[cols].head()

sepal_length  petal_length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4

In [16]:
df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [17]:
df['class'].value_counts()

Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
Name: class, dtype: int64

## Filter

In [18]:
df[df['petal_length'] > 2].head()

sepal_length  sepal_width  petal_length  petal_width            class
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor

In [19]:
len(df[df['petal_length'] > 2])

100

In [20]:
df[(df['petal_length'] > 2)  & (df['petal_length'] <= 4)].head()

sepal_length  sepal_width  petal_length  petal_width            class
53           5.5          2.3           4.0          1.3  Iris-versicolor
57           4.9          2.4           3.3          1.0  Iris-versicolor
59           5.2          2.7           3.9          1.4  Iris-versicolor
60           5.0          2.0           3.5          1.0  Iris-versicolor
62           6.0          2.2           4.0          1.0  Iris-versicolor

## Group By

In [21]:
df.groupby(['class']).mean()

sepal_length  sepal_width  petal_length  petal_width
class                                                                
Iris-setosa             5.006        3.428         1.462        0.246
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [22]:
df.groupby(['class']).count()

sepal_length  sepal_width  petal_length  petal_width
class                                                                
Iris-setosa                50           50            50           50
Iris-versicolor            50           50            50           50
Iris-virginica             50           50            50           50

In [29]:
df[['sepal_length', 'class']].groupby(['class']).agg([np.mean, np.std])

sepal_length          
                        mean       std
class                                 
Iris-setosa            5.006  0.352490
Iris-versicolor        5.936  0.516171
Iris-virginica         6.588  0.635880

## Concatenation

In [24]:
df1 = df[df['class'] == 'Iris-setosa']
df2 = df[df['class'] == 'Iris-virginica']

In [25]:
df1.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [26]:
df2.head()

sepal_length  sepal_width  petal_length  petal_width           class
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica

In [30]:
dfc = pd.concat([df1, df2], axis=0)
dfc['class'].unique()

array(['Iris-setosa', 'Iris-virginica'], dtype=object)

## Merge

In [31]:
df['id'] = [i for i in range(len(df))]

In [32]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class  id
0           5.1          3.5           1.4          0.2  Iris-setosa   0
1           4.9          3.0           1.4          0.2  Iris-setosa   1
2           4.7          3.2           1.3          0.2  Iris-setosa   2
3           4.6          3.1           1.5          0.2  Iris-setosa   3
4           5.0          3.6           1.4          0.2  Iris-setosa   4

In [33]:
df1 = df[df['petal_length'] < 4]
df2 = df[df['petal_length'] > 2]
print(len(df1), len(df2))

61 100


In [34]:
dfm = pd.merge(df1, df2, how='inner', on=['id'])
len(dfm)

11

In [35]:
dfm.head()

sepal_length_x  sepal_width_x  petal_length_x  petal_width_x  \
0             4.9            2.4             3.3            1.0   
1             5.2            2.7             3.9            1.4   
2             5.0            2.0             3.5            1.0   
3             5.6            2.9             3.6            1.3   
4             5.6            2.5             3.9            1.1   

           class_x  id  sepal_length_y  sepal_width_y  petal_length_y  \
0  Iris-versicolor  57             4.9            2.4             3.3   
1  Iris-versicolor  59             5.2            2.7             3.9   
2  Iris-versicolor  60             5.0            2.0             3.5   
3  Iris-versicolor  64             5.6            2.9             3.6   
4  Iris-versicolor  69             5.6            2.5             3.9   

   petal_width_y          class_y  
0            1.0  Iris-versicolor  
1            1.4  Iris-versicolor  
2            1.0  Iris-versicolor  
3            1.3  Iris-versicolor  
4            1.1  Iris-versicolor

## Remove Column

In [36]:
df.drop(['id'], inplace=True, axis=1)

In [37]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Apply function

In [ ]:
class_map = {k: v for v, k in enumerate(df['class'].unique())}

In [ ]:
class_map

In [ ]:
df['class_nbr'] = df['class'].map(class_map)

In [ ]:
df.head()